#!/bin/bash

menu(){
	clear
	echo -e '======================================================= \033[33;1m Select Server  \033[m '
	IFS_OLD=$IFS
	IFS=";"
	while read id ip name color
	do
		shopt -s extglob
		echo -e $id '\033['$color';1m'$name'\033[m' - $ip
	done < $FAST_REMOTE/servers.properties 
	echo -e '======================================================== \033[33;1m More Options  \033[m '
	echo -e 'q - to quit'
	IFS=$IFS_OLD
}

install(){
	define_bash_file
	add_to_bash_file 'export FAST_REMOTE='$PWD;
	add_to_bash_file 'export PATH=$PATH:$FAST_REMOTE'	
	chmod +x $0
	echo "Installation successfully"
	source_bash_file_msg
	echo "usage: fast-remote --help"
}

source_bash_file_msg(){
	echo "Run command: 'source "$HOME/$bash_file"' or logout/login"
}
add_to_bash_file(){
	echo $1 >> $HOME/$bash_file;
}

define_default_user(){
	define_bash_file
	echo "Set default user name"
	read username
	add_to_bash_file 'export DAFAULT_USER_FAST_REMOTE='$username
	source_bash_file_msg
}

define_bash_file(){
	bash_file=".bashrc";
	if [ `uname` = "Darwin" ] ; then
		bash_file=".bash_profile";
	fi
}

help_msg(){
	echo -e "Usage:\n"
	echo -e "'fast-remote install' to install"
	echo -e "'fast-remote set_user' to define default user connect"
	echo -e "'fast-remote' to connect ssh (ssh SERVER)"
	echo -e "'fast-remote /home/user/file.tar' to transfer file scp (scp file SERVER:/HOME_DIR)\n"
}

start(){

	menu

	read option
	server=`cat $FAST_REMOTE/servers.properties | egrep -i "^$option;"`

	if [ $option = "q" ]; then
		exit	   	
	elif [ -z "$server" ]; then
	   	echo "Ivalid option"
	else
		user=$DAFAULT_USER_FAST_REMOTE
		if [ -z $DAFAULT_USER_FAST_REMOTE ]; then
			user=$USER
		fi
		ip=`echo $server | cut -d \; -f 2`
		if [ -z $1 ]; then
			ssh $user@$ip
			start
		fi
		scp $1 $user@$ip:.
	fi
	exit
}

case "$1" in 
	install) install;; 
	set_user) define_default_user;; 
	--help) help_msg;; 
	-h) help_msg;; 
	*) start $1;; 
esac

