#!/bin/bash

menu(){
	clear
	echo -e '======================================================= \033[33;1m Select Server  \033[m '
	IFS_OLD=$IFS
	IFS=";"
	while read id ip name
	do
		color=31
		shopt -s extglob
		if [[ $name == dev* ]]; then
			color=32
		elif [[ $name == h* ]]; then
			color=36
		fi
		echo -e $id '\033['$color';1m'$name'\033[m' - $ip
	done < $NETSITE_UTILS/servers.properties 
	echo -e '======================================================== \033[33;1m More Options  \033[m '
	echo -e 'q - to quit'
	echo -e 'a - add hosts to /etc/hosts'
	IFS=$IFS_OLD
}

add_hosts(){
	su -c "echo '#Start - hosts' >> /etc/hosts;cat $NETSITE_UTILS/servers.properties | sed 's/^.*;\(.*\);\(.*\).*$/\1 \2/' >> /etc/hosts;echo '#End - hosts' >> /etc/hosts"
}

install(){
	echo 'export NETSITE_UTILS='$PWD >> ~/.bashrc
	echo 'PATH=$PATH:$NETSITE_UTILS' >> ~/.bashrc
	chmod +x $0
	echo "Installation successfully"
	echo "usage: fast-remote --help"
	flush_bashrc
}

flush_bashrc(){
	/bin/bash
	#echo "please: run command: source ~/.bashrc"
	#echo ":("
}

define_default_user(){
	echo "Set default user name"
	read username
	echo 'export DAFAULT_USER_FAST_REMOTE='$username >> ~/.bashrc
	flush_bashrc
}

help_app(){
	echo -e "Usage:\n"
	echo -e "'fast-remote install' to install"
	echo -e "'fast-remote set_user' to define default user connect"
	echo -e "'fast-remote' to connect ssh (ssh SERVER)"
	echo -e "'fast-remote /home/user/file.tar' to transfer file scp (scp file SERVER:/home/user)\n"
}

start(){

	menu

	read option
	server=`cat $NETSITE_UTILS/servers.properties | egrep -i "^$option;"`

	if [[ $option = "q" || "x$option" = "x" ]]; then
		exit	   	
	elif [ $option = "a" ]; then
		add_hosts
	elif [ -z $server ]; then
	   	echo "Ivalid option"
	else
		user=$DAFAULT_USER_FAST_REMOTE
		if [ -z $DAFAULT_USER_FAST_REMOTE ]; then
			user=$USER
		fi
		ip=`echo $server | cut -d \; -f 2`
		if [ -z $1 ]; then
			ssh $user@$ip
			start
		fi
		scp $1 $user@$ip:/home/$user
	fi
	exit
}

case "$1" in 
	install) install;; 
	set_user) define_default_user;; 
	--help) help_app;; 
	-h) help_app;; 
	*) start $1;; 
esac

